import React, { useState } from "react";
import { Leaf, Globe, Sun, Moon, ChevronDown, Sparkles, Bot, Layers, Radar, LineChart, Calculator, TrendingUp, ShoppingCart, Zap, Search, Compass } from "lucide-react";
const LANGUAGES=[{code:"en",name:"English",flag:"🇬🇧"},{code:"hi",name:"हिन्दी",flag:"🇮🇳"},{code:"mr",name:"मराठी",flag:"🇮🇳"},{code:"te",name:"తెలుగు",flag:"🇮🇳"},{code:"ta",name:"தமிழ்",flag:"🇮🇳"},{code:"pa",name:"ਪੰਜਾਬੀ",flag:"🇮🇳"}];
export default function GlassHeader({isDark=true,theme="dark",onToggleTheme,lang="en",onChangeLang,activeTab="workspace",onChangeTab,onOpenPricing,onOpenCommandPalette}){
 const [langDropdownOpen,setLangDropdownOpen]=useState(false);
 const navItems=[{id:"workspace",label:"Workspace",icon:Bot,badge:"AI Core"},{id:"intel",label:"3D Field Intel",icon:Compass,badge:"Sentinel-2"},{id:"diag",label:"Diagnostics",icon:Leaf},{id:"sat",label:"3D Satellite",icon:Layers},{id:"map",label:"GIS Radar",icon:Radar},{id:"analytics",label:"Yield Analytics",icon:LineChart},{id:"calc",label:"NPK Calc",icon:Calculator},{id:"mandi",label:"Mandi Telemetry",icon:TrendingUp},{id:"market",label:"Marketplace",icon:ShoppingCart}];
 const nextTheme=theme==="botanical"?"cyber":theme==="cyber"?"monochrome":theme==="monochrome"?"harvest":"botanical";
 return <header className={`sticky top-0 z-40 border-b backdrop-blur-2xl ${isDark?"border-emerald-500/20 bg-[#030705]/85 shadow-[0_10px_35px_rgba(0,0,0,0.6)]":"border-slate-200/80 bg-white/90 shadow-sm shadow-slate-100"}`}>
  <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6">
   <button type="button" className="flex items-center gap-3 text-left" onClick={()=>onChangeTab("workspace")} aria-label="Open Agri Nirvana workspace"><span className={`grid h-10 w-10 sm:h-11 sm:w-11 place-items-center rounded-2xl shadow-lg ${isDark?"bg-gradient-to-br from-emerald-400 via-teal-500 to-cyan-500 text-slate-950":"bg-emerald-600 text-white"}`}><Leaf size={22}/></span><span><span className={`block text-lg sm:text-xl font-black ${isDark?"ai-gradient-text":"ai-gradient-text-light"}`}>Agri Nirvana</span><span className={`block text-[11px] font-medium ${isDark?"text-emerald-400/80":"text-emerald-700"}`}>Precision Agronomy & 3D Telemetry</span></span></button>
   <nav aria-label="Primary navigation" className={`hidden xl:flex items-center gap-1 rounded-2xl p-1 border ${isDark?"bg-[#07170e]/80 border-emerald-500/20":"bg-slate-100/90 border-slate-200"}`}>{navItems.map(({id,label,icon:Icon,badge})=>{const active=activeTab===id;return <button type="button" key={id} onClick={()=>onChangeTab(id)} aria-current={active?"page":undefined} className={`flex items-center gap-1.5 rounded-xl px-3 py-1.5 text-xs font-bold ${active?(isDark?"bg-gradient-to-r from-emerald-500 to-teal-400 text-slate-950":"bg-emerald-600 text-white"):(isDark?"text-slate-300 hover:bg-emerald-950/40":"text-slate-600 hover:bg-white")}`}><Icon size={14}/><span>{label}</span>{badge&&<span className="rounded bg-amber-400/20 px-1 text-[8px] text-amber-700">{badge}</span>}</button>})}</nav>
   <div className="flex items-center gap-2"><button type="button" onClick={()=>onOpenCommandPalette?.()} aria-label="Open command palette" className={`hidden md:flex items-center gap-1.5 rounded-xl border px-2.5 py-1.5 text-xs font-bold ${isDark?"border-emerald-500/20 bg-[#071a10] text-slate-300":"border-slate-200 bg-slate-100 text-slate-700"}`}><Search size={13}/><span>Command</span><kbd className="rounded bg-emerald-500/20 px-1 text-[9px]">⌘K</kbd></button><button type="button" onClick={onOpenPricing} className={`rounded-xl border px-3 py-1.5 text-xs font-extrabold ${isDark?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":"border-slate-300 bg-white text-slate-700"}`}><Zap size={13} className="inline mr-1"/>Plans</button><button type="button" onClick={()=>onToggleTheme?.(nextTheme)} aria-label="Cycle visual theme" className={`rounded-xl border px-2.5 py-1.5 text-xs font-bold ${theme==="cyber"?"bg-slate-900 text-emerald-300":theme==="monochrome"?"bg-black text-white":theme==="harvest"?"bg-amber-50 text-amber-900":"bg-white text-slate-700"}`}>{theme==="cyber"?<Moon size={14}/>:theme==="harvest"?<Sparkles size={14}/>:<Sun size={14}/>}</button><div className="relative"><button type="button" onClick={()=>setLangDropdownOpen(v=>!v)} aria-expanded={langDropdownOpen} aria-haspopup="menu" aria-label="Select language" className={`flex items-center gap-1.5 rounded-xl border px-2.5 py-1.5 text-xs font-bold ${isDark?"border-emerald-500/20 bg-[#071a10] text-slate-200":"border-slate-300 bg-white text-slate-800"}`}><Globe size={14}/><span>{lang.toUpperCase()}</span><ChevronDown size={13}/></button>{langDropdownOpen&&<div role="menu" className="absolute right-0 mt-2 w-40 rounded-2xl border border-slate-200 bg-white p-1 shadow-2xl z-50">{LANGUAGES.map(l=><button type="button" role="menuitem" key={l.code} onClick={()=>{onChangeLang(l.code);setLangDropdownOpen(false)}} className={`flex w-full items-center justify-between rounded-xl px-3 py-2 text-xs ${lang===l.code?"bg-emerald-50 text-emerald-800 font-bold":"text-slate-700 hover:bg-slate-100"}`}><span>{l.name}</span><span>{l.flag}</span></button>)}</div>}</div></div>
  </div>
 </header>;
}
